# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_auto_20161101_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
