# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_auto_20161101_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
