# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0008_auto_20161101_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='chat_app.Chatroom'),
        ),
    ]
