# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=500)),
                ('event_detail', models.CharField(max_length=1000)),
                ('event_date', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', models.CharField(max_length=1000)),
                ('news_text', models.CharField(max_length=1000)),
                ('news_title', models.CharField(max_length=500)),
            ],
        ),
    ]
