# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_events_event_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=30)),
                ('contact_message', models.CharField(max_length=1000)),
            ],
        ),
    ]
