# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_auto_20161101_0006'),
        ('mainpage', '0003_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=500)),
                ('event_detail', models.CharField(max_length=1000)),
                ('event_date', models.CharField(max_length=250)),
                ('event_url', models.CharField(default='', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.Profile')),
            ],
        ),
    ]
