# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('club_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Councils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='clubs',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='councils.Councils'),
        ),
    ]
