# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councils', '0002_achievements_clubevents_clubgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='club_description',
            field=models.CharField(default='No data available', max_length=2000),
        ),
        migrations.AlterField(
            model_name='clubevents',
            name='event_detail',
            field=models.CharField(max_length=2000),
        ),
    ]
